name: Print context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
    print_context:
        runs-on: ubuntu-22.04
        steps:
            - name: Print context
              run: echo "${{ toJSON(github.event) }}"