name: Build & Deploy
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - run: npm ci
            - run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: build
    deploy:
        runs-on: ubuntu-22.04
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: build
            - name: Deploy
              run: echo "Let's think we use build files to deploy" && ls && ls build