name: Deploy app
on:
  push:
    branches: master
#    paths-ignore:
#        - '.github/workflows/*'
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-${{ hashFiles('**/package-lock.json') }}
            - run: npm ci
            - run: npm run test
    lint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Cache deps
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-${{ hashFiles('**/package-lock.json') }}
            - run: npm ci
            - run: npm run lint
    build:
        runs-on: ${{ matrix.os }}
        needs: [test, lint]
        strategy:
            matrix:
                node-version: [16, 18]
                os: [ubuntu-22.04, ubuntu-20.04]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Cache deps
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-${{ hashFiles('**/package-lock.json') }}
            - run: npm ci
            - run: npm run build
            - run: echo "Let's think it's deploying to some place.."